[package]
name = "arcanya"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
colored = "2.1.0"
hashbrown = "0.14.0"
lazy_static = "1.5.0"
nom = "7.1.3"
tiny_http = "0.12.0"
